name: Paname_UHC
version: '${project.version}'
main: ifanoxy.paname_uhc.Paname_UHC
api-version: '1.20'
commands:
  start:
    description: Permet de lancer l'UHC
    usage: /<command>
  setrole:
    description: coucou lol
    usage: /<command> <player/role> <?role>